name: CI

on:
  push:


env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}   
  AWS_AUTHMS_IP: ${{ vars.AWS_AUTHMS_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2

    - name: Set execute permission for gradlew
      run: chmod +x ./LoginMS/gradlew

    - name: Build with Gradle
      run: cd ./LoginMS && ./gradlew assemble

    - name: Archive Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AuthMSBootjar
        path: ./LoginMS/build/libs/SmartCityWasteManagement-0.0.1-SNAPSHOT.jar
  
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set permissions for private key
      run: |
        echo "$AWS_PRIVATE_KEY" > key.pem
        chmod 400 key.pem
        
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: AuthMSBootjar
        path: artifacts

    - name: Stop all running container 
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$AWS_AUTHMS_IP 'sudo docker-compose stop || true'

    - name: Copy new boot jar
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem artifacts/SmartCityWasteManagement-0.0.1-SNAPSHOT.jar ubuntu@$AWS_AUTHMS_IP:/home/ubuntu

    - name: Up the system with all containers
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$AWS_AUTHMS_IP 'cd ~ ; sudo docker-compose up -d'
  
  cleanup:
    runs-on: ubuntu-latest
    needs: [build,deploy]
    steps:
    - name: Delete Artifact
      run: |
        rm -rf AuthMSBootjar
      continue-on-error: true
